###
# schedule list
GET http://localhost:5000/mms/api/schedule HTTP/1.1
content-type: application/json

###
# schedule insert
PUT http://localhost:5000/mms/api/schedule HTTP/1.1
content-type: application/json

{
"departmentId":0, 
"empId":0, 
"postId":0 
}

###
# schedule update
POST http://localhost:5000/mms/api/schedule HTTP/1.1
content-type: application/json

{
"id":24,
"departmentId":0, 
"empId":0, 
"postId":0 
}
###
# schedule delete
DELETE http://localhost:5000/mms/api/schedule HTTP/1.1
content-type: application/json

{
"id":24
}

 