###
# report list
GET http://localhost:5000/mms/api/report HTTP/1.1
content-type: application/json

###
# report insert
PUT http://localhost:5000/mms/api/report HTTP/1.1
content-type: application/json

{
"businessId": 3,
"businessReport": "businessReport"
}

###
# report update
POST http://localhost:5000/mms/api/report HTTP/1.1
content-type: application/json

{
"id":5,
"businessId": 3,
"businessReport": "businessReport2"
}
###
# report delete
DELETE http://localhost:5000/mms/api/report HTTP/1.1
content-type: application/json

{
"id":6
}

 